version: '3.7'

services:
  web:
    image: build .
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ./.env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  static_value:
  media_value: