# Generated by Django 2.2.12 on 2021-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=70, unique=True, verbose_name='ID пользователя')),
                ('name', models.CharField(default='Студент', max_length=15, verbose_name='Обращение')),
                ('faculties', models.CharField(max_length=60, verbose_name='Название факультатива/института')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('year_start_learn', models.IntegerField(verbose_name='Год начала обучения')),
                ('form_of_learn', models.CharField(max_length=2, verbose_name='Форма обучения')),
                ('direction', models.CharField(max_length=3, verbose_name='Направление')),
                ('group', models.IntegerField(verbose_name='Направление')),
            ],
        ),
    ]
