# Generated by Django 3.2.8 on 2021-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
