# Generated by Django 3.2.8 on 2021-10-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='course',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='direction',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='faculties',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Название факультатива/института'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='form_of_learn',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='name',
            field=models.CharField(blank=True, default='Студент', max_length=15, null=True, verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='state',
            field=models.CharField(blank=True, default='Free', max_length=10, null=True, verbose_name='Состояние сессии'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='year_start_learn',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год начала обучения'),
        ),
    ]
